#!/bin/bash
#
# WHICH DISTRO
cat /etc/redhat-release > $RDIR/distrocheck 2>/dev/null || cat /etc/*-release > $RDIR/distrocheck 2>/dev/null || cat /etc/issue > $RDIR/distrocheck 2>/dev/null
grep -i "debian" $RDIR/distrocheck &>/dev/null && REP=APT
grep -i "ubuntu" $RDIR/distrocheck &>/dev/null && REP=APT
grep -i "centos" $RDIR/distrocheck &>/dev/null && REP=YUM
grep -i "red hat" $RDIR/distrocheck &>/dev/null && REP=YUM
grep -i "rocky" /tmp/distrocheck &>/dev/null && REP=YUM
rm $RDIR/distrocheck &>/dev/null

if [ "$REP" = APT ]; then
	apt-get -y install curl
fi
if [ "$REP" = YUM ]; then
	yum -y install curl
fi

