#!/bin/bash

HOST_NAME=$(hostnamectl --static)
RDIR=/usr/local/lcreports/$HOST_NAME
DATE=$(date)

mkdir -p $RDIR

# WHICH DISTRO
cat /etc/redhat-release > $RDIR/distrocheck 2>/dev/null || cat /etc/*-release > $RDIR/distrocheck 2>/dev/null || cat /etc/issue > $RDIR/distrocheck 2>/dev/null
grep -i "debian" $RDIR/distrocheck &>/dev/null && REP=APT
grep -i "ubuntu" $RDIR/distrocheck &>/dev/null && REP=APT
grep -i "centos" $RDIR/distrocheck &>/dev/null && REP=YUM
grep -i "red hat" $RDIR/distrocheck &>/dev/null && REP=YUM
grep -i "rocky" /tmp/distrocheck &>/dev/null && REP=YUM
rm $RDIR/distrocheck &>/dev/null

# UPDATE CONTROL
CHECK_UPDATE=NONE
UPDATE_COUNT=0

if [ "$REP" = APT ]; then
	echo "n" |apt-get upgrade > $RDIR/update_list.txt
	cat $RDIR/update_list.txt |grep "The following packages will be upgraded:" &>/dev/null && CHECK_UPDATE=EXIST \
		&& UPDATE_COUNT=$(cat $RDIR/update_list.txt |grep "upgraded," |cut -d " " -f1)
elif [ "$REP" = YUM ]; then
	yum check-update > $RDIR/update_list.txt
	sed -i '/Loaded/d' $RDIR/update_list.txt
	sed -i '/Loading/d' $RDIR/update_list.txt
	sed -i '/*/d' $RDIR/update_list.txt
	sed -i '/Last metadata/d' $RDIR/update_list.txt
	sed -i '/^$/d' $RDIR/update_list.txt
	UPDATE_COUNT=$(cat $RDIR/update_list.txt |wc -l)
	#rm $RDIR/update_list.txt &>/dev/null

	if [ "$UPDATE_COUNT" -gt 0 ]; then
		CHECK_UPDATE=EXIST
	else
		CHECK_UPDATE=NONE
	fi
fi

# BROKEN PACKAGE CONTROL
BROKEN_COUNT=0
if [ "$REP" = APT ];then
        dpkg -l | grep -v "^ii" &>/dev/null > $RDIR/broken_package.txt
        sed -i -e '1d;2d;3d;4d;5d' $RDIR/broken_package.txt
        BROKEN_COUNT=$(wc -l $RDIR/broken_package.txt |cut -d " " -f1)

        ### ALLOWUNAUTH=$(grep -v "^#" /etc/apt/ -r | grep -c "AllowUnauthenticated")
        ### if [ $ALLOWUNAUTH = 0 ]; then SYS_SCORE=$(($SYS_SCORE + 10)); fi
        ### DEBSIG=$(grep -v "^#" /etc/dpkg/dpkg.cfg |grep -c no-debsig)
        ### if [ $DEBSIG = 1 ]; then SYS_SCORE=$(($SYS_SCORE + 10)); fi
fi

if [ "$REP" = YUM ];then
        rpm -Va >> /dev/null > $RDIR/broken_package.txt
        BROKEN_COUNT=$(wc -l $RDIR/broken_package.txt |cut -d " " -f1)
fi

cat > $RDIR/$HOST_NAME.updatereport << EOF
====================================================================================================
:::. $HOST_NAME UPDATE INFORMATION REPORT :::.
====================================================================================================
$DATE
----------------------------------------------------------------------------------------------------
UPDATE CHECK RESULT   | $CHECK_UPDATE
UPDATE COUNT          | $UPDATE_COUNT
====================================================================================================

EOF

cat >> $RDIR/$HOST_NAME.txt<< EOF

|---------------------------------------------------------------------------------------------------
| ::. Update Info .:: |
|----------------------------------------------------------------------------------------------------
|UPDATE CHECK RESULT   | $CHECK_UPDATE
|UPDATE COUNT          | $UPDATE_COUNT
|----------------------------------------------------------------------------------------------------
EOF

if [ ! "$BROKEN_COUNT" = 0 ];then
	sed -i '$d' $RDIR/$HOST_NAME.updatereport
	echo "|----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.updatereport
	echo "|----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.txt
	echo "|BROKEN PACKAGE COUNT  | $BROKEN_COUNT" >> $RDIR/$HOST_NAME.updatereport
	echo "|BROKEN PACKAGE COUNT  | $BROKEN_COUNT" >> $RDIR/$HOST_NAME.txt
	echo "|----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.updatereport
	echo "|----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.txt
	cat $RDIR/broken_package.txt >> $RDIR/$HOST_NAME.updatereport
	cat $RDIR/broken_package.txt >> $RDIR/$HOST_NAME.txt
	echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.updatereport
	echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.txt
fi

rm $RDIR/update_list.txt &>/dev/null
rm $RDIR/broken_package.txt &>/dev/null
