#!/bin/bash

HOST_NAME=$(hostnamectl --static)
RDIR=/usr/local/lcreports/$HOST_NAME
DATE=$(date)

#############################
# Create System Load Report
#############################
NOC=$(nproc --all)
#LOAD_AVG=$(top -n 1 -b | grep "load average:" |awk -F: '{ print $4 $5 }')
LOAD_AVG=$(uptime |grep "load average:" |awk -F: '{print $5}')

############################
# Create Process Report
############################
#TO_PROCESS=$(top -n 1 -b |grep "Tasks:" |awk '{print $2}')
#RU_PROCESS=$(top -n 1 -b |grep "Tasks:" |awk '{print $4}')
#SL_PROCESS=$(top -n 1 -b |grep "Tasks:" |awk '{print $6}')
ST_PROCESS=$(top -n 1 -b |grep "Tasks:" |awk '{print $8}')
#ZO_PROCESS=$(top -n 1 -b |grep "Tasks:" |awk '{print $10}')
ZO_PROCESS=$(ps -A -ostat,ppid,pid,cmd | grep -e '^[Zz]' | wc -l)

cat > $RDIR/$HOST_NAME.processreport << EOF
====================================================================================================
:::. $HOST_NAME PROCESS REPORT .:::
====================================================================================================
$DATE

----------------------------------------------------------------------------------------------------
|CPU Count:           |$NOC
|System Load Average: |$LOAD_AVG
|Zombie Process:      |$ZO_PROCESS
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
====================================================================================================
EOF

cat >> $RDIR/$HOST_NAME.txt << EOF

|---------------------------------------------------------------------------------------------------
|:::. Process Report .::: |
|---------------------------------------------------------------------------------------------------
|CPU Count:           |$NOC
|System Load Average: |$LOAD_AVG
|Zombie Process:      |$ZO_PROCESS
----------------------------------------------------------------------------------------------------
EOF
