#!/bin/bash

WDIR=/usr/local/lastcontrol
SDIR=$WDIR/scripts
RDIR=/tmp/lastcontrolreports
LCKEY=/root/.ssh/lastcontrol
DATE=$(date)

rm -r $RDIR &>/dev/null
mkdir -p $RDIR

rm $RDIR/linuxhost-unreachable &>/dev/null
rm $WDIR/linuxhost &>/dev/null

NUMMACHINE=$(cat $WDIR/linuxmachine | wc -l)
i=1
while [ "$i" -le "$NUMMACHINE" ]; do
	LINUXMACHINE=$(ls -l |sed -n $i{p} $WDIR/linuxmachine)
	ping $LINUXMACHINE -c 1 &> /dev/null
	pingReturn=$?

	if [ "$pingReturn" -eq 0 ]; then
		ssh -p22 -i $LCKEY -o "StrictHostKeyChecking no" root@$LINUXMACHINE -- exit
		sshReturn=$?
	elif [ "$pingReturn" -eq 1 ]; then
		echo "$LINUXMACHINE Destination Host Unreachable" >> $RDIR/linuxhost-unreachable
	elif [ "$pingReturn" -eq 2 ]; then
		echo "$LINUXMACHINE Hostname could not be resolved" >> $RDIR/linuxhost-unreachable
	elif [ "$sshReturn" -eq 255 ]; then
		echo "$LINUXMACHINE Connection request has been rejected" >> $RDIR/linuxhost-unreachable
	elif [ "$sshReturn" -eq 130 ]; then
		echo "$LINUXMACHINE Permission denied" >> $RDIR/linuxhost-unreachable
	fi
	
	if [ "$pingReturn" -eq 0 ] && [ "$sshReturn" -eq 0 ]; then
		#scp -r -P22 -i /root/.ssh/lastcontrol $SDIR root@$LINUXMACHINE:/tmp/
		#ssh -p22 -i $LCKEY root@$LINUXMACHINE -- bash 'rm -r /tmp/lastcontrol-reports'
		echo $LINUXMACHINE >> $WDIR/linuxhost
	fi

i=$(( i + 1 ))
done
