#!/bin/bash

WDIR=/usr/local/lastcontrol
RDIR=/usr/local/lastcontrolreports
CLSCRIPTS=$WDIR/scripts/cl-scripts
LCKEY=/root/.ssh/lastcontrol

NUMMACHINE=$(cat $WDIR/linuxhost | wc -l)
i=1
while [ "$i" -le "$NUMMACHINE" ]; do
	LINUXMACHINE=$(ls -l |sed -n $i{p} $WDIR/linuxhost)
	
	scp -r -P22 -i $LCKEY $CLSCRIPTS root@$LINUXMACHINE:/usr/local/
	ssh -p22 -i $LCKEY root@$LINUXMACHINE -- bash /usr/local/cl-scripts/run-scripts.sh

	mkdir -p $RDIR/$LINUXMACHINE
	scp -r -P22 -i $LCKEY root@$LINUXMACHINE:/usr/local/lastcontrol-reports/$LINUXMACHINE  /usr/local/lastcontrolreports/

i=$(( i + 1 ))
done
