#!/bin/bash

WDIR=/usr/local/lastcontrol
RDIR=/usr/local/lastcontrolreports
LCSCRIPTS=$WDIR/scripts/lcscripts
LCKEY=/root/.ssh/lastcontrol

NUMMACHINE=$(cat $WDIR/linuxhost | wc -l)
i=1
while [ "$i" -le "$NUMMACHINE" ]; do
	LINUXMACHINE=$(ls -l |sed -n $i{p} $WDIR/linuxhost)
	
	scp -r -P22 -i $LCKEY $LCSCRIPTS root@$LINUXMACHINE:/usr/local/
	ssh -p22 -i $LCKEY root@$LINUXMACHINE -- bash /usr/local/lcscripts/run-scripts.sh

	mkdir -p $RDIR/$LINUXMACHINE
	scp -r -P22 -i $LCKEY root@$LINUXMACHINE:/usr/local/lcreports/$LINUXMACHINE  /usr/local/lastcontrolreports/

	ssh -p22 -i $LCKEY root@$LINUXMACHINE -- bash /usr/local/lcscripts/clear-reports.sh

i=$(( i + 1 ))
done
