#!/bin/bash

WDIR=/usr/local/lastcontrol
RDIR=/tmp/reports
LINE='<hr class="dashed">'
SYSDATE=$(date +%F)
SYSDAY=$(date +%A)
SYSHOUR=$(date +%H:%M)
RDATE="$SYSDATE - $SYSDAY $SYSHOUR"

# GeneralReport html
cat > $RDIR/generalreport.html << EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<html>
<head>
<title>LastControl</title>
</head>
<style>
.DivPageHead {
	border: 1px outset #000000;
	background-color: #D7CCC8;
	text-align: center;
}
table, th, td {
border: 5px solid #D7CCC8;
padding: 10px;
text-align: left;
font-family: quicksand, arial, sans-serif;
font-size: 20px;
margin-top: 20px;
line-height: 1.5em;
}
</style>
<table id="tablereports">
<tr>
<th>Machine Name</th>
<th>System/Distro</th>
<th>Services</th>
<th>Inventory</th>
<th>Vulnerability / Hardening</th>

</tr>
<body>
	<div class="DivPageHead">
		<br>
		<h1>LastControl General Report</h1>
		$RDATE
		<hr />
	</div>
EOF

NUMMACHINE=$(cat $WDIR/linuxhost | wc -l)
i=1
while [ "$i" -le "$NUMMACHINE" ]; do
	LINUXMACHINE=$(ls -l |sed -n $i{p} $WDIR/linuxhost)

	echo "<br>" >> $RDIR/generalreport.html
	echo "<tr>" >> $RDIR/generalreport.html
	echo "<td>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.txt>$LINUXMACHINE</a><br>" >> $RDIR/generalreport.html
	echo "</td>" >> $RDIR/generalreport.html
	
	echo "<td>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.systemreport>System Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.kernelreport>Kernel Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.grubreport>GRUB Report</a><br>" >> $RDIR/generalreport.html
	echo "<br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.localuserreport>Local Users Report</a><br>" >> $RDIR/generalreport.html
	echo "<br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.diskreport>Disk Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.firewallreport>Firewall Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.updatereport>Update Report</a><br>" >> $RDIR/generalreport.html
	echo "</td>" >> $RDIR/generalreport.html
	
	echo "<td>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.servicereport>Service Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.nwconfigreport>Network Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.diskreport>SSH Report</a><br>" >> $RDIR/generalreport.html
	echo "</td>" >> $RDIR/generalreport.html

	echo "<td>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.machineinventory>Inventory Report</a><br>" >> $RDIR/generalreport.html
	echo "</td>" >> $RDIR/generalreport.html

	echo "<td>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.vulnerabilityreport>Vulnerability Analysis Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.unsecurepackreport>UnSecure Pack. Install Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.diskreport>Directory Config Report</a><br>" >> $RDIR/generalreport.html
	echo "<a href=$LINUXMACHINE/$LINUXMACHINE.suidsgidreport>SUID-SGID Files Report</a><br>" >> $RDIR/generalreport.html
	echo "</td>" >> $RDIR/generalreport.html
	
	#echo "</td>" >> $RDIR/generalreport.html
	echo "</tr>" >> $RDIR/generalreport.html
	
i=$(( i + 1 ))
done

#echo "</table>" >> $RDIR/generalreport.html
#echo "</body>" |tee -a $RDIR/inventory.html $RDIR/generalreport.html $RDIR/mainpage.html $RDIR/checkfailed.html >/dev/null
#echo "</html>" |tee -a $RDIR/inventory.html $RDIR/generalreport.html $RDIR/mainpage.html $RDIR/checkfailed.html >/dev/null

echo "</table>" >> $RDIR/generalreport.html &>/dev/null
echo "</body>" >> $RDIR/generalreport.html &>/dev/null
echo "</html>" >> $RDIR/generalreport.html &>/dev/null

rm -r /var/www/html/reports
mkdir -p /var/www/html/reports
RDIR=/var/www/html/reports
cp -r /tmp/reports/* $RDIR/
