#!/bin/bash

HOST_NAME=$(hostnamectl --static)
RDIR=/tmp/lastcontrol-reports/$HOST_NAME
DATE=$(date)

# WHICH DISTRO
cat /etc/redhat-release > $RDIR/distrocheck 2>/dev/null || cat /etc/*-release > $RDIR/distrocheck 2>/dev/null || cat /etc/issue > $RDIR/distrocheck 2>/dev/null
grep -i "debian" $RDIR/distrocheck &>/dev/null && REP=APT
grep -i "ubuntu" $RDIR/distrocheck &>/dev/null && REP=APT
grep -i "centos" $RDIR/distrocheck &>/dev/null && REP=YUM
grep -i "red hat" $RDIR/distrocheck &>/dev/null && REP=YUM
grep -i "rocky" /tmp/distrocheck &>/dev/null && REP=YUM
rm $RDIR/distrocheck &>/dev/null

if [ "$REP" = APT ]; then
	FTP_INSTALL=FALSE
	dpkg -l |grep ftp |grep -v "sftp" &>/dev/null && FTP_INSTALL=TRUE
	TELNET_INSTALL=FALSE
	dpkg -l |grep telnet &>/dev/null && TELNET_INSTALL=TRUE
	RSH_INSTALL=FALSE
	dpkg -l |grep rsh &>/dev/null && RSH_INSTALL=TRUE
	NIS_INSTALL=FALSE
	dpkg -l |grep nis &>/dev/null && NIS_INSTALL=TRUE
	YPTOOLS_INSTALL=FALSE
	dpkg -l |grep yp-tools &>/dev/null && YPTOOLS_INSTALL=TRUE
	XINET_INSTALL=FALSE
	dpkg -l |grep xinet &>/dev/null && XINET_INSTALL=TRUE

elif [ "$REP" = YUM ]; then
	FTP_INSTALL=FALSE
	rpm -qa |grep ftp |grep -v "sftp" &>/dev/null && FTP_INSTALL=TRUE
        TELNET_INSTALL=FALSE
        rpm -qa |grep telnet &>/dev/null && TELNET_INSTALL=TRUE
        RSH_INSTALL=FALSE
        rpm -qa |grep rsh &>/dev/null && RSH_INSTALL=TRUE
        NIS_INSTALL=FALSE
        rpm -qa |grep nis &>/dev/null && NIS_INSTALL=TRUE
        YPTOOLS_INSTALL=FALSE
        rpm -qa |grep yp-tools &>/dev/null && YPTOOLS_INSTALL=TRUE
        XINET_INSTALL=FALSE
        rpm -qa |grep xinet &>/dev/null && XINET_INSTALL=TRUE
fi

cat > $RDIR/$HOST_NAME.unsecurepackreport << EOF
====================================================================================================
:::. $HOST_NAME UNSECURE PACKAGE INSTALLATION REPORT :::.
====================================================================================================
$DATE

----------------------------------------------------------------------------------------------------
|FTP INSTALL:     |$FTP_INSTALL
|TELNET INSTALL:  |$TELNET_INSTALL
|RSH INSTALL:     |$RSH_INSTALL
|NIS INSTALL:     |$NIS_INSTALL
|YPTOOLS INSTALL: |$YPTOOLS_INSTALL
|XINET INSTALL:   |$XINET_INSTALL
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
====================================================================================================
EOF
