#!/bin/bash

HOST_NAME=$(hostnamectl --static)
RDIR=/tmp/lastcontrol-reports/$HOST_NAME
DATE=$(date)

# find suid files
find / -user root -perm -4000 -exec ls -ldb {} \; |awk '{print $1 " - " $3 ":" $4 " - " $9}' > /tmp/suidfiles.txt
# find sgid files
find / -user root -perm -2000 -exec ls -ldb {} \; |awk '{print $1 " - " $3 ":" $4 " - " $9}' > /tmp/sgidfiles.txt
# find suid-sgid files
find / -user root -perm -6000 -exec ls -ldb {} \; |awk '{print $1 " - " $3 ":" $4 " - " $9}' > /tmp/suidsgidfiles.txt


cat > $RDIR/$HOST_NAME.suidsgidreport << EOF
====================================================================================================
:::. $HOST_NAME SUID-SGID File and Directory REPORT :::.
====================================================================================================
$DATE

----------------------------------------------------------------------------------------------------

EOF

echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.suidsgidreport
echo "SUID File List on $HOST_NAME" >> $RDIR/$HOST_NAME.suidsgidreport
echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.suidsgidreport
cat /tmp/suidfiles.txt >> $RDIR/$HOST_NAME.suidsgidreport
echo "" >> $RDIR/$HOST_NAME.suidsgidreport

echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.suidsgidreport
echo "SGID File and Directory List on $HOST_NAME" >> $RDIR/$HOST_NAME.suidsgidreport
echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.suidsgidreport
cat /tmp/sgidfiles.txt >> $RDIR/$HOST_NAME.suidsgidreport
echo "" >> $RDIR/$HOST_NAME.suidsgidreport

echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.suidsgidreport
echo "SUID+SGID File and Directory List on $HOST_NAME" >> $RDIR/$HOST_NAME.suidsgidreport
echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.suidsgidreport
cat /tmp/suidsgidfiles.txt >> $RDIR/$HOST_NAME.suidsgidreport
echo "" >> $RDIR/$HOST_NAME.suidsgidreport

rm /tmp/suidfiles.txt /tmp/sgidfiles.txt /tmp/suidsgidfiles.txt

echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.suidsgidreport
echo "====================================================================================================" >> $RDIR/$HOST_NAME.suidsgidreport
