#!/bin/bash

HOST_NAME=$(hostnamectl --static)
RDIR=/usr/local/lastcontrol-reports/$HOST_NAME
DATE=$(date)

# /tmp directory
mount | grep -E '\s/tmp\s' > /tmp/tmp_mount.txt
if [ "$?" = 0 ]; then
	TMPMOUNT=Pass
	egrep "size=" /tmp/tmp_mount.txt >> /dev/null && TMPSZIE=Used/Pass
	egrep "noexec" /tmp/tmp_mount.txt >> /dev/null && TMPNOEXEC=Used/Pass
else
	TMPMOUNT=Fail
	TMPSIZE=None/Fail
	TMPNOEXEC=None/Fail
fi

# /var directory
mount | grep -E '\s/var\s' >> /dev/null
if [ "$?" = 0 ]; then
	VARMOUNT=Pass
else
	VARMOUNT=Fail
fi

mount | grep -E '\s/var/tmp\s' >> /dev/null
if [ "$?" = 0 ]; then
	VARTMPMOUNT=Pass
else
	VARTMPMOUNT=Fail
fi

mount | grep -E '\s\/var\/log\s' >> /dev/null
if [ "$?" = 0 ]; then
	VARLOGMOUNT=Pass
else
	VARLOGMOUNT=Fail
fi

cat > $RDIR/$HOST_NAME.directoryreport << EOF
====================================================================================================
:::. $HOST_NAME Directory Mount and Config REPORT :::.
====================================================================================================
$DATE

----------------------------------------------------------------------------------------------------
|/tmp Directory is mounted      |$TMPMOUNT
|Size config usage for /tmp     |$TMPSIZE
|NoExec config usage for /tmp   |$TMPNOEXEC
----------------------------------------------------------------------------------------------------
|/var Directory is mounted      |$VARMOUNT
|/var/tmp Directory is mounted  |$VARTMPMOUNT
|/var/log Directory is mounted  |$VARLOGMOUNT
----------------------------------------------------------------------------------------------------

====================================================================================================
EOF

cat >> $RDIR/$HOST_NAME.txt << EOF

|----------------------------------------------------------------------------------------------------
| ::. Directory Mount and Config Info .:: |
|----------------------------------------------------------------------------------------------------
|/tmp Directory is mounted      |$TMPMOUNT
|Size config usage for /tmp     |$TMPSIZE
|NoExec config usage for /tmp   |$TMPNOEXEC
----------------------------------------------------------------------------------------------------
|/var Directory is mounted      |$VARMOUNT
|/var/tmp Directory is mounted  |$VARTMPMOUNT
|/var/log Directory is mounted  |$VARLOGMOUNT
----------------------------------------------------------------------------------------------------

EOF

rm -f /tmp/tmp_mount.txt
