#!/bin/bash

#HOST_NAME=$(hostnamectl --static)
HOST_NAME=$(cat /etc/hostname)
RDIR=/usr/local/lastcontrol-reports/$HOST_NAME
DATE=$(date)

mkdir -p $RDIR

# WHICH DISTRO
cat /etc/redhat-release > $RDIR/distrocheck 2>/dev/null || cat /etc/*-release > $RDIR/distrocheck 2>/dev/null || cat /etc/issue > $RDIR/distrocheck 2>/dev/null
grep -i "debian" $RDIR/distrocheck &>/dev/null && REP=APT && DISTRO=Debian
grep -i "ubuntu" $RDIR/distrocheck &>/dev/null && REP=APT && DISTRO=Ubuntu
grep -i "centos" $RDIR/distrocheck &>/dev/null && REP=YUM && DISTRO=Centos
grep -i "red hat" $RDIR/distrocheck &>/dev/null && REP=YUM && DISTRO=RedHat
grep -i "rocky" /tmp/distrocheck &>/dev/null && REP=YUM && DISTRO=Rocky


cat > $RDIR/$HOST_NAME.localreporeport << EOF
====================================================================================================
:::. $HOST_NAME LOCAL REPOSITORY INFORMATION REPORT :::.
====================================================================================================
$DATE
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
Local Repository List
----------------------------------------------------------------------------------------------------
EOF

cat >> $RDIR/$HOST_NAME.txt<< EOF

|---------------------------------------------------------------------------------------------------
| ::. Local Repository Info .:: 
|---------------------------------------------------------------------------------------------------
EOF

if [ "$REP" = "APT" ]; then 
	grep -rhE ^deb /etc/apt/sources.list* >> $RDIR/$HOST_NAME.localreporeport
	grep -rhE ^deb /etc/apt/sources.list* >> $RDIR/$HOST_NAME.txt
fi

if [ "$REP" = "YUM" ]; then 
	yum repolist >> $RDIR/$HOST_NAME.localreporeport
	yum repolist >> $RDIR/$HOST_NAME.txt
fi


echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.localreporeport
echo "----------------------------------------------------------------------------------------------------" >> $RDIR/$HOST_NAME.txt

rm $RDIR/distrocheck &>/dev/null
