#!/bin/bash

function pause(){
local message="$@"
[ -z $message ] && message="Press Enter to continue"
read -p "$message" readEnterKey
}

function show_menu(){
MACHDATE=$(date)
echo -e "\e[1;37;1m$MACHDATE\e[0m"
pwd
echo "-------------------------------------------------------------------------"
echo ""
BANNERCOLOR=$((1 + "$RANDOM" % 9))
tput setaf "$BANNERCOLOR"
cat /usr/local/lastcontrol/doc/banner.txt
tput setaf 9
echo "    V2 Update:13"
tput sgr0
echo "   |------------------------------------------------------------------------|"
echo "   | # MANAGEMENT MENU #                                                    |"
echo "   |------------------------------------------------------------------------|"
echo "   | 1. Add Machine       | 11. Create Report         | 20. Manage Machine  |"
echo "   | 2. Remove Machine    | 12. Create Machine Report |                     |"
echo "   | 3. Machine List      |                           |                     |"
echo "   |------------------------------------------------------------------------|"
echo "   | # HOST MENU #                                                          |"
echo "   |------------------------------------------------------------------------|"
echo "   | 30. Set static ip    | 40. Disk List                                   |"
echo "   | 31. Show ip          | 41. Add Storage                                 |"
echo "   |                      | 42. Mount List                                  |"
echo "   |------------------------------------------------------------------------|"
tput setaf 9
echo "     99.Exit"
tput sgr0
echo ""
}

function create_report(){
tput setaf 10
echo "LastControl Create Report Starting.."
tput sgr 0
systemctl restart lastcontrol
watch -n 1 systemctl status lastcontrol.service
pause
}


function read_input(){
tput setaf 7
local c
read -p "You can choose from the menu numbers " c
tput sgr0
case $c in
1)      create_container ;;
11)     create_report ;;
99)     exit 0 ;;
*)
tput setaf 1
echo "Please select from the menu numbers"
tput sgr0
pause
esac
}

# CTRL+C, CTRL+Z
trap '' SIGINT SIGQUIT SIGTSTP

while true
do
clear
show_menu
read_input
done
